apiVersion: v1
data:
  repositories: |
    - passwordSecret:
        key: password
        name: git-credentials
      url: https://gitlab.example.com/user/kubernetes
      usernameSecret:
        key: username
        name: git-credentials
  url: http://localhost:4000
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
