apiVersion: argoproj.io/alphav1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
 strategy:
    canary:
      steps:
      - setWeight: 20
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
        - name: VAR1
          value: something
